export enum UserActionType {
    SEARCH_USERS_START = 'SEARCH_USERS_START',
    SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS',
    SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR',

    ADD_USER_START = 'ADD_USER_START',
    ADD_USER_SUCCESS = 'ADD_USER_SUCCESS',
    ADD_USER_ERROR = 'ADD_USER_ERROR',
  }
  